### PR TITLE
bug: macros don't propage to C executables

### LINKED ISSUE #777: bug: preprocess.cpp does not propage macros to compiler
### Description

I am not sure whether this is a bug or I am doing something I am not supposed to but I can't get the `[preprocess]` target from `fpm.toml` to be read during build/run, neither in Fortran nor C.

## MWE

**fpm.toml**
```toml
name = "fpm-preproc-bug"

[library]
include-dir = ["src"]

[[executable]]
name="mwe-c"
main="main.c"

[[executable]]
name="mwe-f90"
main="main.F90"

[preprocess]
[preprocess.cpp]
macros=["VAL"]
suffixes=["F90", "f90", "h", "c"]
directories=["src", "app"]
```

**src/val.h**
```c
#ifndef _VAL_H_
#define _VAL_H_

#ifdef VAL
const int variable = 1;
#else
const int variable = 0;
#endif
#endif
```

**src/valf.h**
```fortran
#ifdef VAL
integer, parameter :: variable = 1
#else
integer, parameter :: variable = 0
#endif
```

**app/main.c**
```c
#include <stdio.h>

#include "val.h"

int main() { printf("%d\n", variable); }
```

**app/main.f90**
```fortran
program main
#include "valf.h"
    print*, variable
end program main
```
[fpm-preproc-bug.zip](https://github.com/fortran-lang/fpm/files/9766138/fpm-preproc-bug.zip)

## Output

```bash
fpm run mwe-f90 --verbose
```
```log
+ mkdir -p build/dependencies
 <INFO> BUILD_NAME: build/gfortran
 <INFO> COMPILER:  gfortran
 <INFO> C COMPILER:  gcc
 <INFO> CXX COMPILER: g++
 <INFO> COMPILER OPTIONS:  -cpp -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single
 <INFO> C COMPILER OPTIONS:  
 <INFO> CXX COMPILER OPTIONS: 
 <INFO> LINKER OPTIONS:  
 <INFO> INCLUDE DIRECTORIES:  [././src]
 + mkdir -p build/gfortran_106D6A1C09440129
 + mkdir -p build/gfortran_F8E64876ACEA9A0D
[  0%]           libfpm-preproc-bug.a
 + mkdir -p build/gfortran_106D6A1C09440129/fpm-preproc-bug/
 + ar -rs build/gfortran_106D6A1C09440129/fpm-preproc-bug/libfpm-preproc-bug.a 
ar: creating build/gfortran_106D6A1C09440129/fpm-preproc-bug/libfpm-preproc-bug.a
[ 20%]           libfpm-preproc-bug.a  done.
[ 20%]                         main.c
 + mkdir -p build/gfortran_F8E64876ACEA9A0D/fpm-preproc-bug/
 + gcc -c app/main.c  -I././src -o build/gfortran_F8E64876ACEA9A0D/fpm-preproc-bug/app_main.c.o
[ 40%]                         main.c  done.
[ 40%]                       main.F90
 + gfortran -c app/main.F90 -cpp -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -I././src -J build/gfortran_106D6A1C09440129 -Ibuild/gfortran_106D6A1C09440129 -o build/gfortran_106D6A1C09440129/fpm-preproc-bug/app_main.F90.o
[ 60%]                       main.F90  done.
[ 60%]                          mwe-c
 + mkdir -p build/gfortran_106D6A1C09440129/app/
 + gfortran -cpp -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -I././src  build/gfortran_F8E64876ACEA9A0D/fpm-preproc-bug/app_main.c.o build/gfortran_106D6A1C09440129/fpm-preproc-bug/libfpm-preproc-bug.a -o build/gfortran_106D6A1C09440129/app/mwe-c
[ 80%]                          mwe-c  done.
[ 80%]                        mwe-f90
 + gfortran -cpp -Wall -Wextra -Wimplicit-interface -fPIC -fmax-errors=1 -g -fcheck=bounds -fcheck=array-temps -fbacktrace -fcoarray=single -I././src  build/gfortran_106D6A1C09440129/fpm-preproc-bug/app_main.F90.o build/gfortran_106D6A1C09440129/fpm-preproc-bug/libfpm-preproc-bug.a -o build/gfortran_106D6A1C09440129/app/mwe-f90
[100%]                        mwe-f90  done.
[100%] Project compiled successfully.
 + build/gfortran_106D6A1C09440129/app/mwe-f90 
           0
```

### Expected Behaviour

The preprocessor macros being passed to the compiler as arguments e.g. `-DVAL` and get an answer of 1 instead of 0.

From this PR https://github.com/fortran-lang/fpm/pull/720 and a quick read, it appears that preprocessor macros should be fully functional

### Version of fpm

https://github.com/fortran-lang/fpm/pull/775

### Platform and Architecture

Linux x64

### Additional Information

Require fpm version from https://github.com/fortran-lang/fpm/pull/775

### PR DESCRIPTION
**Pull request by gnikit**
Fixes #777

### CODE REVIEW

**Review by zoziha — APPROVED** [review]
Thanks for sharing @gnikit , LGTM.

**Review by LKedward — COMMENTED** [review]
Thanks @gnikit, code changes look good to me 👍  Few minor points about the example package:
- Do we need the `stub.c` file for this example?
  - If not, can we move the header file into an `include` subdirectory and simplify the manifest?
- Are you able to update [`example_packages/README.md`](https://github.com/fortran-lang/fpm/blob/main/example_packages/README.md) with the new example packages and why they're needed?

**Comment by gnikit** [comment]
> Thanks @gnikit, code changes look good to me +1 Few minor points about the example package:
> 
> * Do we need the `stub.c` file for this example?
>   
>   * If not, can we move the header file into an `include` subdirectory and simplify the manifest?

I will have a look at this today. BTW we might have a bug in our hands. Unfortunately, I don't have a OS X machine handy anymore so I can't really dig around.

> * Are you able to update [`example_packages/README.md`](https://github.com/fortran-lang/fpm/blob/main/example_packages/README.md) with the new example packages and why they're needed?

Sure thing.

**Review by LKedward — APPROVED** [review]
Brilliant, thanks! All looks good to me 👍

**Pull request merged**
