### PR TITLE
Release version 0.8.0

### PR DESCRIPTION
**Pull request by awvwgk**
Test release at https://github.com/awvwgk/fortran-package-manager/releases/tag/v0.8.0
News post at https://github.com/fortran-lang/fpm-docs/pull/99

### CODE REVIEW

**Comment by perazz** [comment]
Blazingly fast! Thank you @awvwgk, can't wait to see it merged.

**Review by gnikit — APPROVED** [review]
Great work guys, looking forward to the new features making to the official release.

Sebastian @awvwgk I'm away travelling these next few days but I will get the pypi packaging sorted when I get back.

**Comment by awvwgk** [comment]
> I'm away travelling these next few days

Same for me, hope it is not too irresponsible to drop a new release as an easter surprise and then vanish for a couple of days.

**Comment by awvwgk** [comment]
Minh @minh, Federico @perazz, let me know if there are any blockers from your side which prevent releasing this version today.

**Comment by minhqdao** [comment]
> Minh @minhqdao, Federico @perazz, let me know if there are any blockers from your side which prevent releasing this version today.

Not that I'm aware of. 🤔

**Comment by perazz** [comment]
no blockers on my side @awvwgk, thank you.

**Pull request merged**
