### PR TITLE
Catch execute_command_line errors and print useful messages

### PR DESCRIPTION
**Pull request by LKedward**
Adds an `exitstat` argument to the `execute_command_line` wrapper `run` so that failures can be caught and useful messages printed instead of the error stop backtrace.
This makes it much easier to determine which source files failed to compile, or which apps/tests failed to run.

### CODE REVIEW

**Review by awvwgk — APPROVED** [review]
That's a nice improvement, thanks for sharing.

**Comment by LKedward** [comment]
Thanks for the review - I think once this and #497 are merged, it would be a good time for a new release (`0.3.0`).

**Comment by awvwgk** [comment]
I don't see any breaking changes in the CLI or manifest, but just added features and bugfixes, therefore I think it should be `0.2.1`

**Comment by LKedward** [comment]
Ah yes, am I misinterpreting the discussion in #399 - I'd thought we'd bump minor for any changes during 0.x.x?
Also #412 does break *fpm* support for packages that have duplicate modules, but I guess that was never officially supported.

**Comment by awvwgk** [comment]
I think the strategy used in Julia's Pkg is not a bad one for versioning in the pre-1.0 stage: https://pkgdocs.julialang.org/v1/compatibility/#compat-pre-1.0-1. Which means in pre-1.0 same minor versions are mostly compatible.

**Review by milancurcic — APPROVED** [review]
Looks good, thank you! I also thought the next release should be 0.3.0.

**Comment by LKedward** [comment]
Thanks for reviewing, I'll now merge. Will put together a separate PR for bumping the version now.

**Pull request merged**
