### PR TITLE
Bump version to 0.7.0

### PR DESCRIPTION
**Pull request by gnikit**
Test release at: https://github.com/gnikit/fpm/releases/tag/v0.7.0

PR merge instructions: https://github.com/fortran-lang/fpm/wiki/Release-Process

----

As a result of discussion in https://fortran-lang.discourse.group/t/should-fpm-release-versions-more-often/4596 to get features from main and Current release to the conda-forge, homebrew, etc.

## Summary:

- C++ support
- C preprocessor bug fixes
- Minor bug fixes

### CODE REVIEW

**Review by awvwgk — APPROVED** [review]
Looks like the MacOS build in test release failed.

If that is fixed, it seems ready to go. Thanks!

**Comment by gnikit** [comment]
> Looks like the MacOS build in the test release failed. Here the CI is green, so maybe just a temporary issue, best restart it to be sure.
> 
> If that is fixed, it seems ready to go. Thanks!

I think there might be something funny going on with my fpm fork, GitHub Actions and GitHub Apps like pre-commit. I'll restart but FYI pre-commit is not enabled on my fpm fork and it is still running (and failing).

**Comment by gnikit** [comment]
@awvwgk I can't seem to get the macos-latest build to work on my fork. Does the CI fail on your fork too?

**Review by zoziha — APPROVED** [review]
Good to see fpm-0.7.0 released soon :)

* I just merged #783, which fixes a bug related to preprocessor settings, suitable for being relegated to `fpm-0.7.0`;
* Does [`winget`](https://github.com/microsoft/winget-pkgs) also need to be considered as a release channel for `fpm`? (https://github.com/fortran-lang/fpm/discussions/744)

**Review by LKedward — APPROVED** [review]

**Comment by LKedward** [comment]
Thanks @gnikit!
The MacOS running here is 11 whereas in your fork it's 12 which is likely causing the issue. I think Brad said that the latest MacOS runner image has changed the gfortran installation. Perhaps try specifying `macos-11` in your fork to pin the version instead of `macos-latest`?

**Comment by awvwgk** [comment]
> Does [`winget`](https://github.com/microsoft/winget-pkgs) also need to be considered as a release channel for `fpm`? (#744)

While we have not contributed the package to winget, it would be good if we document the update workflow when somebody figures out how to do it. For now I would leave it as external distribution channel we are not directly responsible for.

> I can't seem to get the macos-latest build to work on my fork. Does the CI fail on your fork too?

Works fine on my fork, maybe you have subscribed to some beta preview which affects MacOS runners? But I think it doesn't matter much, let's merge and see how it goes.

**Comment by gnikit** [comment]
@awvwgk It seems to have worked ok. I'll do the release in `fortran-lang/fpm` in a bit

**Pull request merged**
