### PR TITLE
Update developer documentation (manifest + command line)

### PR DESCRIPTION
**Pull request by awvwgk**
Now that @milancurcic has created https://fpm.fortran-lang.org we should populate the documentation a bit. I will make a start with the manifest and the command line.

- populate the landing page at https://fpm.fortran-lang.org
- link with the TOML homepage and describe the package manifest format
- sketch the implementation of the TOML parsing and link to TOML-Fortran
- describe the scope of *fpm* with respect to the package manifest
- link with the M_CLI2 repository and describe the command line interface
- add a short documentation on the usage of M_CLI2 for the command line
- describe the process of adding new subcommands and arguments
- outline the generation of the developer pages and link to the FORD wiki

### CODE REVIEW

**Comment by urbanjost** [comment]
Up till now I had put the calls to M_CLI2 in.  Recently the `include` command was added without any assist from me, so their might be some fresh insights there on how hard that was to do. I have used something M_CLI2 was drawn from (M_kracken) for so long it is almost a reflex for me to use it. But I can put something together pretty quickly on how to add a new subcommand if you like. I have not gone back to add direct support of subcommands in M_CLI2. That is something it does not directly support as a feature, but I thought it has held up well enough so far (and recently was compiled with ifort, nvfortran, and nagfor and appears to work) so

**Comment by awvwgk** [comment]
Another big thing would be the documentation of the model and the build process, @LKedward would you like to write something on this or should I give it a try? However I would make the documentation of the model and build process a separate PR.

**Comment by LKedward** [comment]
> Another big thing would be the documentation of the model and the build process, @LKedward would you like to write something on this or should I give it a try?

Yep I would be happy to :+1:. I'll start work for a separate PR - should I add to `docs.md` or create a new page?

**Comment by awvwgk** [comment]
My strategy in this PR is to create a small introduction on the landing page regarding all important aspects of *fpm*, so far the manifest, command line and the documentation, and link to the respective parts in the pages, the module docs or external resources, whatever is appropriate and most useful.

**Review by LKedward — APPROVED** [review]
Thanks @awvwgk, this all looks good :+1: 

(I've made a start on adding developer documentation to the 'middle-end' <https://github.com/LKedward/fpm/tree/dev-docs-model>)

**Comment by LKedward** [comment]
This is a great start on improving (creating) the developer documentation and doesn't contain any code changes so I'll now merge. Thanks @awvwgk. I'll have a PR building on this soon.

**Pull request merged**
