### PR TITLE
Update README.md compiler, archiver, & link flags

### PR DESCRIPTION
**Pull request by rouson**
This PR completes and updates the README.md description of the above `fpm` flags to match the description given by `fpm build --help`.

### CODE REVIEW

**Review by milancurcic — APPROVED** [review]
Thank you @rouson, this looks great.

I wonder about the README info being out of sync with the latest release. These env. variables are currently only available from the `main` branch, but not in 0.4.0. A user downloading the latest release binary could be confused why these env variables from the README don't work.

I don't know if we have had a discussion or workflow for this situation. Some ideas on how to work around this:

* `main` is always == latest release and all development features go into a release candiate branch (e.g. `rc-0.5.0`). or
* New release on every new feature merge.

@awvwgk @LKedward what do you think?

**Review by LKedward — APPROVED** [review]
Thanks Damian @rouson - looks good to me 👍 

---

Yes, I think that issue has cropped up before @milancurcic . My preferred solution would be for development on a separate `dev` branch or release candidate as you suggest.

**Comment by rouson** [comment]
One way to mitigate the problem @milancurcic identified is to release more often. In agile sprints, releases happen every 2-3 weeks.  If the main branch is always releasable, there's little downside other than the labor involved, which can be lessened by automated any labor-intensive aspects of releasing.

**Comment by LKedward** [comment]
With two reviews I'll now merge this PR. Thanks everyone.

**Pull request merged**
