### PR TITLE
Fix broken link in contributing guidelines

### LINKED ISSUE #340: Link in contributing guide is broken
> You can learn how from this [great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github).

The link at the end of the contributing is broken. The correct address is:

https://app.egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github

### PR DESCRIPTION
**Pull request by awvwgk**
Closes #340

### CODE REVIEW

**Review by LKedward — APPROVED** [review]
LGTM, thanks 👍

**Comment by LKedward** [comment]
CI passes after rerunning so not sure if there's some non-determinism (?) in the tests. Think it was the 'help_test' that failed. (This test is actually a little problematic since it invokes `fpm run` to run Fortran *fpm*, but this doesn't test the release flags properly.)

**Comment by awvwgk** [comment]
> Think it was the 'help_test' that failed. (This test is actually a little problematic since it invokes `fpm run` to run Fortran _fpm_, but this doesn't test the release flags properly.)

I opened #343 to discuss this.

**Comment by awvwgk** [comment]
Since this is a simple change, I'll go ahead and merge.

**Pull request merged**
