### PR TITLE
Release 0.8.1

### PR DESCRIPTION
**Pull request by perazz**
Test release at https://github.com/perazz/fpm/releases/tag/v0.8.1
Announcement at https://github.com/fortran-lang/fpm-docs/pull/101

cf. #872

### CODE REVIEW

**Comment by everythingfunctional** [comment]
My guess is you will actually need 2 flags when you're building up the dependency list.

1. Is this the cached version?
2. Is this the first time I'm encountering this dependency

That way you only update the dependency if it doesn't match the cached version **and** it is the first version encountered when walking the tree.

**Comment by perazz** [comment]
Aaah I think I found where the issue is from. Commit 1f604b4 introduced undefined behavior (removed `fetch=.false.` by default) in `dependency%register`, apparently in all the tests I've made so far that was always `.true.` by complete chance!

**Comment by perazz** [comment]
Brad @everythingfunctional what should I do with this bugfix? merge into my release branch directly, or open a new PR on fpm main?

**Comment by perazz** [comment]
Release suspended due to #875, will open a new PR for that.

**Pull request merged**
