### PR TITLE
use `clang` in lieu of `gcc` as C compiler for homebrew-openmpi action

### LINKED ISSUE #939: Failing CI: (macOS) Install homebrew OpenMPI
### Description

The CI fails while trying to install OpenMPI on macOS via homebrew.

It also takes forever (47m 36s until failure).

https://github.com/fortran-lang/fpm/actions/runs/5271571352/jobs/9532646356?pr=937

@perazz 

### Expected Behaviour

It doesn't fail.

It's done super quickly.

### Version of fpm

The one used in the CI

### Platform and Architecture

macOS

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by perazz**
Fixes #939.

Successful action running in 29 seconds: https://github.com/perazz/fpm/actions/runs/5303750239/jobs/9599600174

### CODE REVIEW

**Review by henilp105 — APPROVED** [review]
Thanks @perazz , looks good to me.

**Comment by perazz** [comment]
Will see after merging if this remains valid, but the issue appears solved after replacing all boolean `HOMEBREW_*` environemnt variables from `"ON"` with `1`.

**Review by awvwgk — APPROVED** [review]
Thanks for the update

**Comment by perazz** [comment]
Thank you @awvwgk @henilp105, merging this. Will keep an eye on this one.

**Pull request merged**
