### PR TITLE
Add workflow for continuous delivery

### PR DESCRIPTION
**Pull request by awvwgk**
Since our default branch is always deployable, we can easily create a continuous release which contains the latest fpm binaries and source version. This PR adds a workflow to create and move a tag called `current` with the head of the git repository and update the binary artifacts to the latest CI outputs.

Example: https://github.com/awvwgk/fortran-package-manager/releases/tag/current

### CODE REVIEW

**Comment by awvwgk** [comment]
@rouson, would a continuous delivery resolve #416 for you?

**Comment by LKedward** [comment]
Thanks Sebastian @awvwgk, this would be very useful. Quick question: is this restricted to the main branch? I can see anything that would prevent it running on pushes to other branches.

**Comment by awvwgk** [comment]
It will run on any push event, this includes feature branches on forks. Since we only have a single branch in the main repository this is not an issue (now), but it enables contributors to make use of building continuous releases on their forks for testing purposes. We can limit it to the main branch of course if this is a concern.

**Comment by LKedward** [comment]
> ... it enables contributors to make use of building continuous releases on their forks for testing purposes

I can see the benefit of this for testing, however I don't like the fact that the `current` tag would be dependent on which ever branch the workflow most recently ran on - or have I misunderstood this? I think we should either have a different tag per branch or restrict the workflow to only run on the default branch. What do you think?

**Comment by awvwgk** [comment]
I added a dependency on a repository secret `DEPLOY_BRANCH` which will be used to determine whether a branch should be deployed or not. If the secret is not set no branch should be deployed. We would set it to `refs/heads/main` here to only deploy the default branch, but someone could set it to `refs/heads` at their fork to deploy all branches or to `refs/heads/devel` to deploy only the *devel* branch.

**Comment by rouson** [comment]
> @rouson, would a continuous delivery resolve #416 for you?

I'm just realizing that I never responded to the above question.   I'm not familiar with continuous release, but from what is described here, yes.  I think this would solve issue. #416 for me.

**Review by LKedward — APPROVED** [review]
Thanks Sebastian, LGTM 👍

Is it possible to link to the `current` release download page from the README or does it change with each deployment?

**Review by milancurcic — APPROVED** [review]
Great, thank you! I don't understand all the details of the CI.yml, but agree with the overall strategy. Please merge when ready.

**Pull request merged**
