### PR TITLE
Redirect output when searching for archiver

### PR DESCRIPTION
**Pull request by awvwgk**
Requires some shuffling of routines to avoid dependency cycles.

Fixes https://github.com/fortran-lang/fpm/issues/456

### CODE REVIEW

**Review by LKedward — APPROVED** [review]
Looks good to me, thanks! :+1:

**Comment by brocolis** [comment]
Thanks @awvwgk, it works great in my default environment. However, when I switch to the Intel oneAPI environment, remove GCC toolchain from the PATH and run `fpm build --compiler ifort`, it displays the message "`ar` is not recognized as an internal or external command, operable program or batch file." After that, the build continues and ends successfully.

```
C:\Temp\test5>fpm build --compiler ifort
 + mkdir build\dependencies
'ar' is not recognized as an internal or external command, operable program or batch file.
 + mkdir build\ifort_782887A201FCE169\test5
 + ifort -c test\check.f90 /warn:all /check:all …
```

**Comment by awvwgk** [comment]
@brocolis should be fixed now.

**Comment by brocolis** [comment]
I've tested the patch in 3 environments, they all work well, thanks @awvwgk 👍
| Toolchain available on PATH |  fpm test --compiler gfortran | fpm test --compiler ifort | fpm test --compiler ifx |
| -------------- | ------------- |------ |------|
| MinGW |  ✅   |  -  | -   |
| oneAPI | -  | ✅   | ✅   |
| oneAPI + MinGW |✅ | ✅   | ✅   |

In environments (1) and (3), `fpm` executes `ar`, while in environment (2), `fpm` executes `lib`. I think the use of `ar` in (3) is a bit inconsistent but it does not cause harm so far and can be resolved later.

**Comment by brocolis** [comment]
In scenario (4), MinGW is found on PATH before Intel oneAPI. It's unusual but it works also.

| Toolchain available on PATH |  fpm test --compiler gfortran | fpm test --compiler ifort | fpm test --compiler ifx |
| -------------- | ------------- |------ |------|
| MinGW |  ✅   |  -  | -   |
| oneAPI | -  | ✅   | ✅   |
| oneAPI + MinGW |✅ | ✅   | ✅   |
| MinGW + oneAPI |✅ | ✅   | ✅   |

**Comment by LKedward** [comment]
Thanks for the thorough testing @brocolis! With that I'll now merge

**Pull request merged**
