### PR TITLE
Add ability to specify which test or program to run and their args

### PR DESCRIPTION
**Pull request by everythingfunctional**
This adds some command line arguments to allow specifying which executable or test you would like to run, and any command line arguments you would like to pass on.

### CODE REVIEW

**Comment by everythingfunctional** [comment]
At this stage I (we) haven't really talked about whether executables should be in their own directory. So that is kind of a current edge case bug.

Right now it just assumes that for a given executable, everything else in that directory is a module meant to be included with it. So while trying to compile one executable it saw the source for the other, assumed it was a module, and failed when compiling it didn't result in the appropriate mod file (or at least I'm guessing that's what happened).

I'd suggest creating an issue so we can discuss and decide whether this should be documented as a limitation/requirement or marked as a bug to fix later.

**Comment by certik** [comment]
Right. We should also consult how Rust does it.

+1 to merge this PR.

**Comment by milancurcic** [comment]
I now see approval from @certik, so I agree to merge this, and we can add some basic instructions to the README in a separate PR.

**Comment by certik** [comment]
See #83 for improving the tests in general. We have to add a lot more tests, that would serve as the "spec" of how fpm is expected to work.

**Comment by everythingfunctional** [comment]
I'll go ahead and add stuff to the README for this PR. No sense leaving it half done.

As for the testing, I think there's just one last thing I'd like to take a crack. I want to get support for using a build script or makefile. That shouldn't take much time to implement. Then yes, we should focus our efforts on writing as many tests (both happy path and error conditions) as we can think of.

Up to this point, this has been a prototype. I think we've been incredibly successful with it, and it's functionality is pretty much right where we want. So now we just put some tests around it to make sure nothing breaks while we pretty up the insides.

**Comment by LKedward** [comment]
> Right now it just assumes that for a given executable, everything else in that directory is a module meant to be included with it. So while trying to compile one executable it saw the source for the other, assumed it was a module, and failed when compiling it didn't result in the appropriate mod file (or at least I'm guessing that's what happened).
> 
> I'd suggest creating an issue so we can discuss and decide whether this should be documented as a limitation/requirement or marked as a bug to fix later.

Thanks for the explanation, this behaviour makes more sense to me now; I don't think it's a bug but it is definitely something that needs to be documented in PACKAGING.md.

**Comment by certik** [comment]
So `cargo build` does not build tests. You have to do `cargo build --tests` to also build tests.

`cargo test` build tests (if needed) and runs them.

I suggest we follow the same approach.

**Comment by everythingfunctional** [comment]
Ok. That will require some (minor) refactoring to get working properly. Open an issue and I can fix it in another PR.

**Comment by certik** [comment]
Sure: #92.

**Pull request merged**
