### PR TITLE
Always initialize `redirect_str` to prevent memory leak

### LINKED ISSUE #1022: Memory profiling reveals multiple "Conditional jump or move depends on uninitialised value(s)" errors
### Description

Cloning the repository today (d3dd5d431d39eb9ba1110b67822d05993c68912f), building fpm and running:
```
fpm new mypackage --app --test
cd mypackage
valgrind fpm run
```

I get several errors:
```
==1091327== Memcheck, a memory error detector
==1091327== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1091327== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==1091327== Command: fpm run
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x4D31CF2: _gfortran_execute_command_line_i4 (in /usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0)
==1091327==    by 0x13FDC3: __fpm_filesystem_MOD_run (fpm_filesystem.F90:1031)
==1091327==    by 0x145AB3: __fpm_filesystem_MOD_is_dir (fpm_filesystem.F90:219)
==1091327==    by 0x1A2E0E: __fpm_manifest_MOD_get_package_data (manifest.f90:145)
==1091327==    by 0x1365C6: __fpm_MOD_cmd_run (fpm.f90:491)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x4D31CF2: _gfortran_execute_command_line_i4 (in /usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0)
==1091327==    by 0x13FDC3: __fpm_filesystem_MOD_run (fpm_filesystem.F90:1031)
==1091327==    by 0x145AB3: __fpm_filesystem_MOD_is_dir (fpm_filesystem.F90:219)
==1091327==    by 0x1A2FF8: __fpm_manifest_MOD_get_package_data (manifest.f90:145)
==1091327==    by 0x1365C6: __fpm_MOD_cmd_run (fpm.f90:491)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x1A3000: __fpm_manifest_MOD_get_package_data (manifest.f90:145)
==1091327==    by 0x1365C6: __fpm_MOD_cmd_run (fpm.f90:491)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x1A3000: __fpm_manifest_MOD_get_package_data (manifest.f90:145)
==1091327==    by 0x132BB8: __fpm_MOD_build_model (fpm.f90:103)
==1091327==    by 0x136692: __fpm_MOD_cmd_run (fpm.f90:496)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x4D31CF2: _gfortran_execute_command_line_i4 (in /usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0)
==1091327==    by 0x13FDC3: __fpm_filesystem_MOD_run (fpm_filesystem.F90:1031)
==1091327==    by 0x145AB3: __fpm_filesystem_MOD_is_dir (fpm_filesystem.F90:219)
==1091327==    by 0x134B87: __fpm_MOD_build_model (fpm.f90:176)
==1091327==    by 0x136692: __fpm_MOD_cmd_run (fpm.f90:496)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x134B8A: __fpm_MOD_build_model (fpm.f90:176)
==1091327==    by 0x136692: __fpm_MOD_cmd_run (fpm.f90:496)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x4D31CF2: _gfortran_execute_command_line_i4 (in /usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0)
==1091327==    by 0x13FDC3: __fpm_filesystem_MOD_run (fpm_filesystem.F90:1031)
==1091327==    by 0x145AB3: __fpm_filesystem_MOD_is_dir (fpm_filesystem.F90:219)
==1091327==    by 0x134C38: __fpm_MOD_build_model (fpm.f90:186)
==1091327==    by 0x136692: __fpm_MOD_cmd_run (fpm.f90:496)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x4D31CF2: _gfortran_execute_command_line_i4 (in /usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0)
==1091327==    by 0x13FDC3: __fpm_filesystem_MOD_run (fpm_filesystem.F90:1031)
==1091327==    by 0x145AB3: __fpm_filesystem_MOD_is_dir (fpm_filesystem.F90:219)
==1091327==    by 0x134CE8: __fpm_MOD_build_model (fpm.f90:196)
==1091327==    by 0x136692: __fpm_MOD_cmd_run (fpm.f90:496)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x4D31CF2: _gfortran_execute_command_line_i4 (in /usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0)
==1091327==    by 0x13FDC3: __fpm_filesystem_MOD_run (fpm_filesystem.F90:1031)
==1091327==    by 0x145AB3: __fpm_filesystem_MOD_is_dir (fpm_filesystem.F90:219)
==1091327==    by 0x145C4C: __fpm_filesystem_MOD_mkdir (fpm_filesystem.F90:380)
==1091327==    by 0x23E027: __fpm_backend_MOD_build_package (fpm_backend.F90:82)
==1091327==    by 0x13706E: __fpm_MOD_cmd_run (fpm.f90:601)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x145C4F: __fpm_filesystem_MOD_mkdir (fpm_filesystem.F90:380)
==1091327==    by 0x23E027: __fpm_backend_MOD_build_package (fpm_backend.F90:82)
==1091327==    by 0x13706E: __fpm_MOD_cmd_run (fpm.f90:601)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
Project is up to date
 hello from project mypackage
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x4D31CF2: _gfortran_execute_command_line_i4 (in /usr/lib/x86_64-linux-gnu/libgfortran.so.5.0.0)
==1091327==    by 0x13FDC3: __fpm_filesystem_MOD_run (fpm_filesystem.F90:1031)
==1091327==    by 0x1374DC: __fpm_MOD_cmd_run (fpm.f90:623)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== Conditional jump or move depends on uninitialised value(s)
==1091327==    at 0x137522: __fpm_MOD_cmd_run (fpm.f90:631)
==1091327==    by 0x115F36: MAIN__ (main.f90:78)
==1091327==    by 0x11549E: main (main.f90:13)
==1091327== 
==1091327== 
==1091327== HEAP SUMMARY:
==1091327==     in use at exit: 83,503 bytes in 475 blocks
==1091327==   total heap usage: 6,621 allocs, 6,146 frees, 900,720 bytes allocated
==1091327== 
==1091327== LEAK SUMMARY:
==1091327==    definitely lost: 6,331 bytes in 391 blocks
==1091327==    indirectly lost: 1,712 bytes in 30 blocks
==1091327==      possibly lost: 0 bytes in 0 blocks
==1091327==    still reachable: 75,460 bytes in 54 blocks
==1091327==         suppressed: 0 bytes in 0 blocks
==1091327== Rerun with --leak-check=full to see details of leaked memory
==1091327== 
==1091327== Use --track-origins=yes to see where uninitialised values come from
==1091327== For lists of detected and suppressed errors, rerun with: -s
==1091327== ERROR SUMMARY: 16 errors from 12 contexts (suppressed: 0 from 0)
```

### Expected Behaviour

I expect no memory errors.

### Version of fpm

d3dd5d431d39eb9ba1110b67822d05993c68912f

### Platform and Architecture

Ubuntu 22.04

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by perazz**
Attempt to fix #1022.

### CODE REVIEW

**Review by henilp105 — APPROVED** [review]
Thanks @perazz , looks good to me.

**Comment by perazz** [comment]
@zoziha I don't know what branch `dependabot/github_actions/JamesIves/github-pages-deploy-action-4.6.0` is for, but it seems like by changing to it, several older commits have been brought into this PR. should we go back to `main` instead?

**Comment by zoziha** [comment]
Sorry, I was using my phone's github app to watch PR content and a screen mishit occurred, causing this change.

**Review by zoziha — APPROVED** [review]
Looks good.

**Pull request merged**
