### PR TITLE
Fix bug with case in program source file name.

### LINKED ISSUE #116: fortran main name file
I found an issue related to the name of the main fortran file.
When main.f90 is in the app directory, the executable is created nicely. Part of the fpm.toml file is:
> [[executable]]
> name="TEST_dnS.x"
> source-dir="app"
> main="main.f90"

However, when, I'm using another name (TEST_dnS.f90)
> [[executable]]
> name="TEST_dnS.x"
> source-dir="app"
> main="TEST_dnS.f90"

I've got some errors:
>fpm: Error when running Shake build system:
>  at want, called at src/Build.hs:114:11 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
> * Depends on: build/gfortran_debug/app/TEST_dnS.x
>  at need, called at src/Build.hs:120:13 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
> * Depends on: build/gfortran_debug/app/test_dns.o
>  at &%>, called at src/Build.hs:137:11 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
> * Depends on: build/gfortran_debug/app/test_dns.o build/gfortran_debug/app/test_dns.mod
>  at undefined, called at src/Build.hs:142:25 in fpm-0.1.0.0-ExRRX9W2aflLvTBBChPpxh:Build
>  at error, called at libraries/base/GHC/Err.hs:78:14 in base:GHC.Err
> * Raised the exception:
> Prelude.undefined

### PR DESCRIPTION
**Pull request by everythingfunctional**
Fix #116

I guess up to now nobody had tried using uppercase in the name of their program source file. This fixes it.

### CODE REVIEW

**Comment by urbanjost** [comment]
Nice timing. This was vexing me and I had just found the work-around and was going to report the bug.  Guess it is time to update my copy of fpm(1). That raises the question of whether there should be a line to put in the input files indicating what version of fpm(1) was tested with (which might produce a warning) and what version is at (at least) required? I would change the pathname back to containing uppercase letters but I am it would confuse anyone attempting to use the repository with an older version of fpm(1), for example.  I was working on setting up the following for use with fpm(1). I see others have mentioned at least supporting C wrappers for use with the intrinsic module ISO_C_BINDING; but unless that is imminent does
anyone have an example using a custom build script that does that? I have a bunch of stuff (M_system, M_draw, M_ncurses, ... that has C wrappers or bindings that I wanted to try with fpm(1) but that is a show stopper; whereas STACK has good multi-language support, etc..

    [dependencies]
     M_process      = { git = "https://github.com/urbanjost/M_process.git" }

I have a bunch of stuff I was trying with fpm(1) so if anyone has time to comment on how I have used (abused?) it so far, M_process and M_time are about done as far as what I was planning on.

Any kind of an image to place on pages that support fpm(1)? A glowing box with light coming out of it with a big "F" above the box?  Anyone feeling artistic?

**Comment by everythingfunctional** [comment]
@urbanjost , I have an example wrapping a C library [here](https://gitlab.com/everythingfunctional/sqliteff).

If I can find some free time I'll try and give your project a look.

**Comment by milancurcic** [comment]
@certik can you please review this or approve without review? This fix allows some users to build their packages.

**Comment by certik** [comment]
This looks good, the fix is simple and tests pass.

**Comment by urbanjost** [comment]
The C wrapper and Makefile and fpm example project file are great. It was not clear from the documentation I had found so far how to do that. I wil see how far I get in the next few days.  Not knowing how to do this was preventing me from going much further with my fpm experiments.

**Pull request merged**
