### PR TITLE
Implement reading of fpm.toml

### LINKED ISSUE #149: TOML parser
Part of #136 

I found 2, both support TOML v0.5 spec:

* [toml-f](https://github.com/awvwgk/toml-f) which is pure Fortran, but unfortunately GPLv3-licensed. We could ask the author to offer a more permissive license beside GPL.
* [f_tomlc99](https://github.com/gregfi/f_tomlc99) which interfaces a C parser. MIT-licensed.

So each presents an integration challenge.

### PR DESCRIPTION
**Pull request by awvwgk**
Uses my [TOML library](https://github.com/toml-f/toml-f) to read the `fpm.toml` file and creates a Fortran type representing the TOML document.

*This PR adds `toml-f` as dependency to `fpm`.*

Closes #149

### CODE REVIEW

**Comment by milancurcic** [comment]
This is super exciting, thanks a lot @awvwgk! I look forward to reviewing it.

**Comment by awvwgk** [comment]
Not sure on the scope of this PR, currently it allows to translate and verify any TOML document as `fpm` package file, but does not do much with this information.

The next step would be to pull in a dependency and translate and verify its `fpm.toml` file, which would require to create new `fpm` instances to recursively build the complete dependency tree. Giving the `git_target_t` a fetch method is easy, but working with the created target is a bit more involved, so this might be somewhat out-of-scope for this PR.

Regarding coding style, any conventions I should apply (indentation)?

**Comment by certik** [comment]
@awvwgk thanks a lot for this PR! We will review it soon. I think the scope is ok as it is, and we can build upon it with further PRs once it is merged.

**Comment by awvwgk** [comment]
Guess it is ready for review than.

The current style guide I'm mostly following is this one: https://github.com/dftbplus/develguide/blob/master/docs/fortranstyle.rst

**Comment by milancurcic** [comment]
We follow the [stdlib style guide](https://github.com/fortran-lang/stdlib/blob/master/STYLE_GUIDE.md). I skimmed through the contributions and didn't see anything that jumps out except the indentation width (we use 4).

**Comment by awvwgk** [comment]
Thanks, this is helpful. I've amended the commit accordingly to keep the history clean.

**Comment by everythingfunctional** [comment]
I didn't dive super deep into it, but from the high level, it looks reasonably similar to the Haskell version, so I think it's probably at least headed in the right direction.

I do have one question though. Would it be possible to write some unit tests for this? Feed it a toml string and make sure the package object is correct, feed it bad toml and make sure it reports an error, etc.

**Comment by awvwgk** [comment]
Sure can do.

**Comment by everythingfunctional** [comment]
That looks good for now. I was hoping it wouldn't require writing to the file, but it's ok for now. It's a slick little minimalist testing framework you put together too.

**Review by everythingfunctional — APPROVED** [review]

**Comment by awvwgk** [comment]
`toml_parse` can read a string too, but it would require to overload or bypass the `read_package_file` procedure just for testing. Having a dedicated version for testing `toml-f` in `fpm` but not the actual version used for `fpm` somewhat defeats the purpose of the test for me, therefore writing the file it is.

I need to work on a better constructor for `toml_table` types upstream so one can easily build a TOML document without having to read it from a file. But this is something for a future PR once I figured it out in `toml-f`.

**Review by LKedward — APPROVED** [review]
Great work @awvwgk! This all looks good to me. Good to see schema checks with useful error messages and a verbose mode.

My only (minor) complaint is naming with `config` where I would have used `manifest` (_e.g._ `fpm_manifest`) to better describe, and distinguish from the existing `settings` types used for command line. What do others think?

Due to the size of this PR I would recommend this be merged prior to mine and other PRs; I will rebase.

**Comment by awvwgk** [comment]
Good idea, `manifest` is probably a better name than `config`, I will adjust this.

**Comment by milancurcic** [comment]
@awvwgk @everythingfunctional @LKedward Should this PR go before or after #155? Is either way easier than the other? I can't tell.

**Comment by LKedward** [comment]
I think this PR should go first because it's bigger. I'll then merge the changes into my branch. (Only conflict between the two is `fpm.f90` I think.)

**Comment by awvwgk** [comment]
They are solving different problems, the order does not matter too much, but a conflict in `fpm.f90` is inevitable, due to the current status of the project.

Since #155 is attempting to add the functionality of fpm building itself, the question arises if we can retain this functionality with both PRs merged. In this regard my PR is working exactly against #155, due to adding an external dependency.

**Comment by LKedward** [comment]
> Since #155 is attempting to add the functionality of fpm building itself, the question arises if we can retain this functionality with both PRs merged. In this regard my PR is working exactly against #155, due to adding an external dependency.

This isn't a problem; parsing the manifest is more important than Fortran `fpm` building itself.
I already know what changes I need to make in #155 once this PR is merged, hence why I recommend that this be merged first.

**Comment by everythingfunctional** [comment]
If @LKedward is happy to rebase his branch and fix the conflicts, I'd go with this one first. As much as I'd like to have fpm be able to build itself, it's not strictly necessary. We'll get there.

**Review by milancurcic — APPROVED** [review]

**Comment by milancurcic** [comment]
I agree. Let's wait to see if @certik has any objections, and if not we can move forward.

**Comment by awvwgk** [comment]
I did a quick coverage run on this PR ([coverage.txt](https://github.com/fortran-lang/fpm/files/5176857/coverage.txt)) and spotted a few issues which were simple oversights. The coverage is currently around 60%, so definitely something to improve.

**Comment by certik** [comment]
I am fine as long as @LKedward is fine, and it seems he his. So we can go ahead and merge this one.

**Comment by awvwgk** [comment]
Also ready from my side now. I decided to pin the revision of `toml-f` to a specific commit to ensure that I won't break fpm by upstream `toml-f`.

**Comment by milancurcic** [comment]
Thank you all and especially @awvwgk. Merging.

**Pull request merged**
