### PR TITLE
Additional testing

### PR DESCRIPTION
**Pull request by everythingfunctional**
Set up and test some example projects

### CODE REVIEW

**Comment by everythingfunctional** [comment]
I think this is now sufficient for any project, with no dependencies, on any platform. But please feel free to put it through the ringer and let me know if you find anything.

**Comment by certik** [comment]
Thanks @everythingfunctional. I'll test it out soon. I was really busy with other things lately.

**Comment by milancurcic** [comment]
I just noticed this didn't make it to master yet. I will play with it. So far I worked only with current master.

**Comment by everythingfunctional** [comment]
@certik , do you want a chance to test it out, or should I go ahead and merge this?

**Pull request merged**
