### PR TITLE
Updated formatting

### PR DESCRIPTION
**Pull request by interkosmos**
Please review these updates of `README.md`, `CONTRIBUTING.md`, and `PACKAGING.md`. Some minor changes in formatting and typography have been made.

### CODE REVIEW

**Comment by milancurcic** [comment]
Thanks, Philipp. I skimmed through and have no objections. To confirm, there are no content changes, right? If not, I think it can go forward.

**Comment by interkosmos** [comment]
Nope, no content changes.

**Review by certik — APPROVED** [review]
Thanks!

**Comment by milancurcic** [comment]
Simple PR with no change to behavior or content so I will go ahead and merge.

**Pull request merged**
